# Phase 2: Data Quality Assessment

## 1. Objective

The objective of this phase is to evaluate the quality and reliability of the e-commerce datasets before performing data cleaning and analysis.

We will examine the datasets for missing values, duplicate records, incorrect data types, inconsistent values, suspicious records, and relationship issues between the datasets.

## 2. Datasets

This assessment covers two datasets:

* **Products Dataset:** Contains product information, including category, description, weight, and dimensions.
* **Order Items Dataset:** Contains order-item information, including product IDs, seller IDs, prices, freight values, and shipping limit dates.

## 3. Assessment Approach

We will inspect the original datasets without modifying them. Any identified quality issues will be documented for further investigation and resolution during the data cleaning phase.

### Step 2: Import libraries and load the datasets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
products = pd.read_csv('../data/raw_data/products.csv')
order_items = pd.read_csv('../data/raw_data/order-items.csv')
print("Datasets loaded successfully!")

Datasets loaded successfully!

In [3]:
print("Products dataset:", products.shape)
print("Order Items dataset:", order_items.shape)

Products dataset: (32341, 9)
Order Items dataset: (57373, 9)

In [8]:
products.head()

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625.0,20.0,17.0,13.0

In [11]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [9]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_weight
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.90,13.29,cool_stuff,650.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,5/3/2017 11:05,239.90,19.93,pet_shop,30000.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,1/18/2018 14:48,199.00,17.87,moveis_decoracao,3050.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,8/15/2018 10:10,12.99,12.79,perfumaria,200.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2/13/2017 13:57,199.90,18.14,ferramentas_jardim,3750.0

In [12]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_weight'],
      dtype='object')

 ### Step 3: Check the dataset structur

In [4]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32341 entries, 0 to 32340
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32341 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_length         32341 non-null  int64
 3   product_description_length  32341 non-null  int64
 4   product_photos_qty          32341 non-null  int64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(4), int64(3), object(2)
memory usage: 2.2+ MB

In [5]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57373 entries, 0 to 57372
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               57373 non-null  object
 1   order_item_id          57373 non-null  int64
 2   product_id             57373 non-null  object
 3   seller_id              57373 non-null  object
 4   shipping_limit_date    57373 non-null  object
 5   price                  57373 non-null  float64
 6   freight_value          57373 non-null  float64
 7   product_category_name  15946 non-null  object
 8   product_weight         15946 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 3.9+ MB

## Step 4: Check missing values

In [6]:
# Check missing values in Products dataset
products_missing = pd.DataFrame({
    "Missing Count": products.isnull().sum(),
    "Missing Percentage": (products.isnull().sum()/len(products) * 100).round(2)
})

print(products_missing[products_missing["Missing Count"] > 0])

                   Missing Count  Missing Percentage
product_weight_g               1                 0.0
product_length_cm              1                 0.0
product_height_cm              1                 0.0
product_width_cm               1                 0.0

In [9]:
# Check missing values in Order Items dataset
order_items_missing = pd.DataFrame({
    "Missing Count": order_items.isnull().sum(),
    "Missing Percentage": (order_items.isnull().sum()/len(order_items) * 100).round(2)
})

print(order_items_missing[order_items_missing["Missing Count"] > 0])

                       Missing Count  Missing Percentage
product_category_name          41427               72.21
product_weight                 41427               72.21

## 2. Step 5 — Investigate missing values